# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "351bdf7cc833597f68f42343af76346c"
name = "pc-builder-dev"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
