# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "14fa5dd8e7343a710c4198be96d225df"
name = "Pc builder"

#client_id = "351bdf7cc833597f68f42343af76346c"
#name = "pc-builder-dev"

application_url = "https://emma-aggressive-don-nano.trycloudflare.com"
embedded = true
#handle="pc-builder-4"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sandeepthedev.myshopify.com"

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_app_proxy, write_discounts, read_discounts"

[auth]
redirect_urls = [
  "https://emma-aggressive-don-nano.trycloudflare.com/auth/callback",
  "https://emma-aggressive-don-nano.trycloudflare.com/auth/shopify/callback",
  "https://emma-aggressive-don-nano.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://emma-aggressive-don-nano.trycloudflare.com"
subpath = "pc-builder"
prefix = "apps"

[pos]
embedded = false
